console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'

[secondary_prompt]
  template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
  foreground = 'p:black'
  background = 'transparent'

[transient_prompt]
  foreground_templates = [
	"{{if gt .Code 0}}red{{end}}",
	"{{if eq .Code 0}}magenta{{end}}",
  ]
  foreground = 'p:magenta'
  background = 'transparent'
  template = "› "
[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  foreground = 'p:white'
  background = 'p:orange'
  type = 'aws'
  style = 'diamond'
  tips = ['aws']

  [tooltips.properties]
    display_default = true

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '
  foreground = 'p:white'
  background = 'p:blue'
  type = 'az'
  style = 'diamond'
  tips = ['az']

  [tooltips.properties]
    display_default = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:blue'
    background = 'transparent'
    template = '{{ .Path }}'

   [blocks.segments.properties]
     style = 'full'
   
  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "#6c6c6c"
    background = "transparent"
    template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}↓{{ end }}{{ if gt .Ahead 0 }}↑{{ end }}</>"

     [blocks.segments.properties]
       fetch_status = true
       fetch_upstream_icon = true
       source = "cli"
       branch_icon = ''

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'
  
  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    template = '{{ .FormattedMs}}'
	
    [blocks.segments.properties]
      threshold = 5000
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
	"{{if gt .Code 0}}red{{end}}",
	"{{if eq .Code 0}}magenta{{end}}",
    ]
    foreground = 'magenta'
    background = 'transparent'
    template = "›"

    
